type: entities
entities:
  - type: custom:multiple-entity-row
    name: Environment
    entity: sensor.prusheen_coop_temperature
    state_header: Temperature
    secondary_info: last-updated
    entities:
      - entity: sensor.prusheen_coop_climate_battery
        name: Battery
      - entity: sensor.prusheen_coop_humidity
        name: Humidity
  - !include rows/room-climate.yaml
  - !include rows/filament-drawer-climate.yaml
  - !include rows/filament-climate.yaml
  - !include rows/coop-door.yaml
