packages:
  device-base: !include device-base.yaml
  shelly1-platform: !include components/shelly1-platform.yaml

light:
  - platform: binary
    id: shelly_relay_light
    name: "${friendly_name}"
    output: shelly_relay

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_relay

binary_sensor:
  - platform: gpio
    internal: true
    pin: GPIO5
    # small delay to prevent debouncing
    filters:
      - delayed_on_off: 50ms
    # config for state change of input button
    on_state:
      then:
        - light.toggle: shelly_relay_light
    id: button
