esp32:
  board: esp-wrover-kit

power_supply:
  - id: backlight_power
    keep_on_time: 0.2s
    enable_time: 0s
    pin:
      mcp23xxx: mcp23017_hub
      number: 11

output:
  - platform: mcp47a1
    id: backlight_brightness_output
    power_supply: backlight_power

light:
  - platform: monochromatic
    output: backlight_brightness_output
    id: backlight
    default_transition_length: 0.2s
    name: "${friendly_name} Backlight"

i2c:

mcp23017:
  - id: mcp23017_hub
    address: 0x20

script:
  - id: turn_on_backlight
    mode: restart
    then:
      - light.turn_on: backlight
      - delay: 1min
      - light.turn_off: backlight

touchscreen:
  - platform: ektf2232
    interrupt_pin: GPIO36
    rts_pin:
      mcp23xxx: mcp23017_hub
      number: 10
    on_touch:
      - logger.log:
          format: "touch x=%d, y=%d"
          args: ["touch.x", "touch.y"]
      - script.execute: turn_on_backlight
