- alias: "[Transmission] Notify completed torrent"
  trigger:
    platform: event
    event_type: transmission_downloaded_torrent
  action:
    - service: notify.notify
      data:
        message: "{{trigger.event.data.name}}"
        title: "Torrent downloaded"
        data:
          url: https://bydlenka.totoro.family/transmission/web/
