blueprint:
  name: ZHA - IKEA Styrbar - Warm White Lights
  description: Control a light with white spectrum and dimming via a Ikea Styrbar
    Remote connected trough ZHA
  domain: automation
  input:
    remote:
      name: IKEA Styrbar remote control
      description: Select the remote control you wish to use.
      selector:
        device:
          filter:
            - integration: zha
              manufacturer: IKEA of Sweden
              model: Remote Control N2
          multiple: false
    light:
      name: Light
      description: Select the light entity you wish to control.
      selector:
        entity:
          filter:
            - domain: light
          multiple: false
  source_url: https://community.home-assistant.io/t/zha-ikea-styrbar-warm-white-lights/341688
mode: restart
max_exceeded: silent
variables:
  var_light: !input 'light'
trigger:
- trigger: event
  event_type: zha_event
  event_data:
    device_id: !input 'remote'
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "on" }}'
    sequence:
    - action: light.turn_on
      target:
        entity_id: !input 'light'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "off" }}'
    sequence:
    - action: light.turn_off
      target:
        entity_id: !input 'light'
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move_with_on_off" }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - action: light.turn_on
          target:
            entity_id: !input 'light'
          data:
            brightness_step_pct: 10
            transition: 0.5
        - delay:
            milliseconds: 500
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "move" }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - action: light.turn_on
          target:
            entity_id: !input 'light'
          data:
            brightness_step_pct: -10
            transition: 0.5
        - delay:
            milliseconds: 500
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [256,13,0] }}'
    sequence:
    - action: light.turn_on
      target:
        entity_id: !input 'light'
      data:
        color_temp: "{% if state_attr(var_light, \"color_temp\") - 25 < 153 %}\n \
          \ {{ 153 }}\n{% else %}\n  {{ state_attr(var_light, \"color_temp\") - 25\
          \ }}\n{% endif %}"
        transition: 0.5
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3328,0] }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - action: light.turn_on
          target:
            entity_id: !input 'light'
          data:
            color_temp: "{% if state_attr(var_light, \"color_temp\") - 25 < 153 %}\n\
              \  {{ 153 }}\n{% else %}\n  {{ state_attr(var_light, \"color_temp\"\
              ) - 25 }}\n{% endif %}"
            transition: 0.5
        - delay:
            milliseconds: 500
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "press" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [257,13,0] }}'
    sequence:
    - action: light.turn_on
      target:
        entity_id: !input 'light'
      data:
        color_temp: "{% if state_attr(var_light, \"color_temp\") + 25 > 500 %}\n \
          \ {{ 500 }}\n{% else %}\n  {{ state_attr(var_light, \"color_temp\") + 25\
          \ }}\n{% endif %}"
        transition: 0.5
  - conditions:
    - condition: template
      value_template: '{{ trigger.event.data.command == "hold" }}'
    - condition: template
      value_template: '{{ trigger.event.data.args == [3329,0] }}'
    sequence:
    - repeat:
        while: []
        sequence:
        - action: light.turn_on
          target:
            entity_id: !input 'light'
          data:
            color_temp: "{% if state_attr(var_light, \"color_temp\") + 25 > 500 %}\n\
              \  {{ 500 }}\n{% else %}\n  {{ state_attr(var_light, \"color_temp\"\
              ) + 25 }}\n{% endif %}"
            transition: 0.5
        - delay:
            milliseconds: 500
  default: []
