resource: !secret golemio_stop1
headers:
  X-Access-Token: !secret golemio_apikey
params:
  minutesAfter: 60
  minutesBefore: -4
  filter: routeOnceFill
sensor:
  - name: Transit stop1 name
    unique_id: transit_stop1_name
    value_template: "{{ value_json.stops[0].stop_name }}"

  - name: Transit stop1 departure0
    unique_id: transit_stop1_departure0
    value_template: "{{ value_json.departures[0].departure_timestamp.predicted }}"
  - name: Transit stop1 departure0 route
    unique_id: transit_stop1_departure0_route
    value_template: >
      {{ value_json.departures[0].route.short_name }} to 
      {{ value_json.departures[0].trip.headsign }}

  - name: Transit stop1 departure1
    unique_id: transit_stop1_departure1
    value_template: "{{ value_json.departures[1].departure_timestamp.predicted }}"
  - name: Transit stop1 departure1 route
    unique_id: transit_stop1_departure1_route
    value_template: >
      {{ value_json.departures[1].route.short_name }} to 
      {{ value_json.departures[1].trip.headsign }}

  - name: Transit stop1 departure2
    unique_id: transit_stop1_departure2
    value_template: "{{ value_json.departures[2].departure_timestamp.predicted }}"
  - name: Transit stop1 departure2 route
    unique_id: transit_stop1_departure2_route
    value_template: >
      {{ value_json.departures[2].route.short_name }} to 
      {{ value_json.departures[2].trip.headsign }}

  - name: Transit stop1 departure3
    unique_id: transit_stop1_departure3
    value_template: "{{ value_json.departures[3].departure_timestamp.predicted }}"
  - name: Transit stop1 departure3 route
    unique_id: transit_stop1_departure3_route
    value_template: >
      {{ value_json.departures[3].route.short_name }} to 
      {{ value_json.departures[3].trip.headsign }}

  - name: Transit stop1 departure4
    unique_id: transit_stop1_departure4
    value_template: "{{ value_json.departures[4].departure_timestamp.predicted }}"
  - name: Transit stop1 departure4 route
    unique_id: transit_stop1_departure4_route
    value_template: >
      {{ value_json.departures[4].route.short_name }} to 
      {{ value_json.departures[4].trip.headsign }}
