substitutions:
  name: entryway-inkplate
  friendly_name: Entryway Inkplate

esphome:
  includes:
    - entryway-inkplate.h

packages:
  device-base: !include common/device-base.yaml
  inkplate6-platform: !include common/components/inkplate6-platform.yaml

time:
  - platform: homeassistant
    id: esptime

switch:
  - platform: restart
    name: "${friendly_name} Reboot"
    id: reboot

  - platform: template
    name: "${friendly_name} Greyscale mode"
    lambda: return id(inkplate_display).get_greyscale();
    turn_on_action:
      - lambda: id(inkplate_display).set_greyscale(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_greyscale(false);

  - platform: template
    name: "Inkplate Partial Updating"
    lambda: return id(inkplate_display).get_partial_updating();
    turn_on_action:
      - lambda: id(inkplate_display).set_partial_updating(true);
    turn_off_action:
      - lambda: id(inkplate_display).set_partial_updating(false);
      
  - platform: gpio
    name: 'Inkplate Touchscreen Enabled'
    restore_mode: ALWAYS_ON
    pin:
      mcp23xxx: mcp23017_hub
      number: 12
      inverted: true


binary_sensor:
  - platform: status
    name: "${friendly_name} Status"
    id: system_status
    
  - platform: homeassistant
    name: Bathroom
    id: bathroom_window
    entity_id: binary_sensor.bathroom_window

  - platform: homeassistant
    name: Bedroom
    id: bedroom_windows
    entity_id: binary_sensor.bedroom_windows

  - platform: homeassistant
    name: Gallery
    id: gallery_window
    entity_id: binary_sensor.gallery_window

  - platform: homeassistant
    name: Guestroom
    id: guestroom_windows
    entity_id: binary_sensor.guestroom_windows

  - platform: homeassistant
    name: Living room
    id: living_room_windows
    entity_id: binary_sensor.living_room_windows

  - platform: homeassistant
    name: Dining room
    id: dining_room_windows
    entity_id: binary_sensor.dining_room_windows

  - platform: homeassistant
    name: Fridge door
    id: fridge_door
    entity_id: binary_sensor.fridge_door

text_sensor:
  - platform: homeassistant
    name: Cooktop
    id: cooktop
    entity_id: sensor.cooktop_status
  - platform: homeassistant
    name: Oven
    id: oven
    entity_id: sensor.oven

font:
  - file: "fonts/DIN_Alternate_Bold.ttf"
    id: default_font
    size: 42

image:
  - file: totoro.png
    id: totoro
    type: grayscale

display:
- platform: inkplate6
  id: inkplate_display
  greyscale: false
  partial_updating: true
  update_interval: 30s
  model: inkplate_6_plus
  rotation: 90

  ckv_pin: 32
  sph_pin: 33
  gmod_pin:
    mcp23xxx: mcp23017_hub
    number: 1
  gpio0_enable_pin:
    mcp23xxx: mcp23017_hub
    number: 8
  oe_pin:
    mcp23xxx: mcp23017_hub
    number: 0
  spv_pin:
    mcp23xxx: mcp23017_hub
    number: 2
  powerup_pin:
    mcp23xxx: mcp23017_hub
    number: 4
  wakeup_pin:
    mcp23xxx: mcp23017_hub
    number: 3
  vcom_pin:
    mcp23xxx: mcp23017_hub
    number: 5

  lambda: |-
    MainPage(it).draw();