substitutions:
  name: "experiment-motors"
  friendly_name: "Experiment - motors"

packages:
  device-base: !include common/device-base.yaml
  # d1-platform: !include common/components/d1-platform.yaml
  d32-platform: !include common/components/d32-platform.yaml

output:
  - platform: ledc
    id: motor_forward_pin
    pin: GPIO18
    frequency: 100kHz
  - platform: ledc
    id: motor_reverse_pin
    pin: GPIO19
    frequency: 100kHz

fan:
  - platform: hbridge
    id: my_fan
    name: "Test motor"
    pin_a: motor_forward_pin
    pin_b: motor_reverse_pin
    # enable_pin: motor_enable
    decay_mode: slow   # slow decay mode (braking) or fast decay (coasting).