substitutions:
  name: "filament-dryer"
  friendly_name: "Filament dryer"

packages: { device-base: !include common/device-base.yaml }
esp8266: { board: esp01_1m }

dallas: [pin: GPIO5]

sensor:
  - platform: dallas
    address: 0x8B011920DFA15D28
    name: "Filament Dryer Temperature"
