substitutions:
  name: 'light-kitchen-sink'
  friendly_name: 'Kitchen sink light'
  light_entity_id: light.kitchen_all

packages:
  shelly1-detached-light-mometary: !include common/shelly1-detached-light-momentary.yaml
