substitutions:
  name: prusheen-lcd
  friendly_name: Prusheen LCD

external_components:
  - source:
      type: local
      path: components

packages:
  device-base: !include common/device-base.yaml
  d32-platform: !include common/components/d32-platform.yaml

prusa_lcd:
  data_pins:
    - GPIO21
    - GPIO17
    - GPIO22
    - GPIO16
  enable_pin: GPIO19
  rs_pin: GPIO18
  text_sensors:
    - name: "Line 1"
    - name: "Line 2"
    - name: "Line 3"
    - name: "Line 4"
