substitutions:
  name: 'prusheen-minicam'
  friendly_name: 'Prusheen Minicam'

packages:
  device-base: !include common/device-minimal.yaml

esp32:
  board: esp32cam
  framework:
    type: arduino

esp32_camera:
  name: Prusheen minicam
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  jpeg_quality: 20
  resolution: 1280x1024
  vertical_flip: true
  horizontal_mirror: true

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot
    
output:
  - platform: ledc
    pin: GPIO4
    channel: 2 # channel 1 is used for esp32_camera
    id: led

light:
  - platform: monochromatic
    output: led
    name: Prusheen minicam light
