substitutions:
  name: prusheen-lcd
  friendly_name: Prusheen LCD

external_components:
  - source: github://the-ress/prusa-lcd-reader@main
    refresh: 0s
    components:
      - prusa_lcd

packages:
  device-base: !include common/device-base.yaml
  d32-platform: !include common/components/d32-platform.yaml

prusa_lcd:
  data_pins:
    - GPIO21
    - GPIO17
    - GPIO22
    - GPIO16
  enable_pin: GPIO19
  rs_pin: GPIO18
  text_sensors:
    - name: "Line 1"
    - name: "Line 2"
    - name: "Line 3"
    - name: "Line 4"
