substitutions:
  name: "soldering-extractor-fan"
  friendly_name: "Soldering extractor fan"
packages: { device-base: !include common/device-base.yaml }
esp32: { board: esp32-c3-devkitm-1 }

esphome:
  on_boot:
    priority: 300
    then:
    - fan.turn_on:
        id: fan_speed
        speed: 100

output:
  # fan speed output (internal entity)
  - platform: ledc
    id: pwm_output
    pin: GPIO4
    frequency: 25 kHz

fan:
  - platform: speed
    output: pwm_output
    name: "Fan Speed"
    id: fan_speed

sensor:
  - platform: pulse_counter
    pin: GPIO3
    name: "Actual Fan Speed"
    unit_of_measurement: "RPM"
    entity_category: diagnostic
    update_interval: 5s
    filters:
      - multiply: 0.5
