substitutions:
  name: switch-bedroom-ceiling
  friendly_name: 'Bedroom ceiling switch'
  light_entity_id: light.bedroom_ceiling
  group_id: light.bedroom_all

packages:
  shelly1-light: !include common/shelly1-switch-momentary.yaml

