substitutions:
  name: "temperature-dining-room"
  friendly_name: "Dining room temperature"
packages: { device-base: !include common/device-base.yaml }
esp8266: { board: esp01_1m }
dallas: [pin: GPIO5]
sensor:
  - platform: dallas
    address: 0x7c011920eae3b128
    name: "Dining room temperature"
  - platform: dallas
    address: 0x3b011920e861fd28
    name: "Dining room radiator temperature"
  - platform: dallas
    address: 0xe8011920eb163628
    name: "Outdoors temperature"

